import extracttexttonumber as en
from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver import ActionChains
driver = webdriver.Chrome(
    'C:/Users/HP/Desktop/Drivers/chromedriver_win32/chromedriver.exe')
driver.maximize_window()
driver.get('https://nad.ndml.in/NAD/studentRegistrationWithOutAaddhaar.html')
# PERSONAL DETAILS
name = driver.find_element_by_xpath('//*[@id="first_name"]')
name.send_keys('shyam bansal')
fathername = driver.find_element_by_xpath('//*[@id="father_name"]')
fathername.send_keys('sanjeev bansal')
mothername = driver.find_element_by_xpath('//*[@id="nsm_mother_f_name0"]')
mothername.send_keys('radhika bansal')
action = ActionChains(driver)
dobs = driver.find_element_by_id('dob')
action.double_click(dobs).perform()
month = driver.find_element_by_class_name('monthselect')
monthdrp = Select(month)
monthdrp.select_by_visible_text('Nov')
year = driver.find_element_by_class_name('yearselect')
yeardrp = Select(year)
yeardrp.select_by_visible_text('2002')
dates = driver.find_element_by_xpath(
    '/html/body/div[2]/div[1]/div[2]/table/tbody/tr[1]/td[1]')
dates.click()
gen = driver.find_element_by_id('gender')
gendrp = Select(gen)
gendrp.select_by_visible_text('Male')
# COMMUNICATION DETAILS
mobilenumber = driver.find_element_by_xpath('//*[@id="mobile_number"]')
mobilenumber.send_keys('9657965723')
emailid = driver.find_element_by_xpath('// *[@id="email_id"]')
emailid.send_keys('ku.shyambansal@gmail.com')
address1 = driver.find_element_by_xpath('//*[@id="address1"]')
address1.send_keys('omax')
address2 = driver.find_element_by_xpath('//*[@id="address2"]')
address2.send_keys('near atalachungi')
city = driver.find_element_by_xpath('//*[@id = "city"]')
city.send_keys('pochinki')
st = driver.find_element_by_id('state')
stdrp = Select(st)
stdrp.select_by_visible_text('Bihar')
pincode = driver.find_element_by_xpath('//*[@id="pincode"]')
pincode.send_keys('281212')
# SELECT ACADEMIC INSTITUTION
institutetype = driver.find_element_by_id('nsm_ai_Type')
institutetypedrp = Select(institutetype)
institutetypedrp.select_by_visible_text('University')
state = driver.find_element_by_id('nsm_univ_state')
statedrp = Select(state)
statedrp.select_by_visible_text('Uttar Pradesh')
time.sleep(4)
nameofinstitution = driver.find_element_by_name('nsm_brd_univ_id')
nameofinstitutiondrp = Select(nameofinstitution)
nameofinstitutiondrp.select_by_visible_text('Allahabad State University')
coursename = driver.find_element_by_xpath('//*[@id="nsm_degree_cd"]')
coursename.send_keys('B tech')
yearofjoining = driver.find_element_by_xpath('//*[@id="year_of_passing"]')
yearofjoining.send_keys('2018')
rollno = driver.find_element_by_xpath('//*[@id="unique_ref_no"]')
rollno.send_keys('E18ECE002')
collegename = driver.find_element_by_xpath('//*[@id="nsm_school_name"]')
collegename.send_keys('Allahabad State University')
# upload files
photo = driver.find_element_by_id('browsImg')
photo.send_keys('C:/Users/HP/Desktop/dog.jpg')
sign = driver.find_element_by_id('browsSig')
sign.send_keys('C:/Users/HP/Desktop/dog.jpg')
# CREATE YOUR LOG-IN DETAILS
userid = driver.find_element_by_xpath('//*[@id="user_id"]')
userid.send_keys('abhishiva')
psd = driver.find_element_by_xpath('//*[@id="user_passwordClone2"]')
psd.send_keys('radhika1234@1234')
cpsd = driver.find_element_by_xpath('//*[@id="confirm_passwordClone3"]')
cpsd.send_keys('radhika1234@1234')
agree = driver.find_element_by_id('checkboxInput')
agree.click()
driver.save_screenshot('C:/Users/HP/Desktop/screenshot/hi.jpg')
time.sleep(5)
captchatext = en.textotnumber("C:/Users/HP/Desktop/screenshot/hi.jpg")
captcha = driver.find_element_by_xpath('//*[@id="captch_code"]')
captcha.send_keys(captchatext)
time.sleep(5)
submit = driver.find_element_by_xpath('//*[@id="btn-submit-reg"]')
submit.click()
